language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed viethainguyentran/udagram-api-feed:v1
  - docker tag udagram-api-user viethainguyentran/udagram-api-user:v1
  - docker tag udagram-frontend viethainguyentran/udagram-frontend:v1
  - docker tag reverseproxy viethainguyentran/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push viethainguyentran/udagram-api-feed:v1
  - docker push viethainguyentran/udagram-api-user:v1
  - docker push viethainguyentran/udagram-frontend:v1
  - docker push viethainguyentran/udagram-reverseproxy:v1