apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api
  labels:
    app: udagram-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user-api
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
      - name: udagram-user-api
        image: viethainguyentran/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: mysecret
          - configMapRef:
              name: config-secret
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m