apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
  labels:
    app: udagram-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
      - name: udagram-feed-api
        image: viethainguyentran/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - secretRef:
              name: mysecret
          - configMapRef:
              name: config-secret
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret