apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8100
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: udagram-frontend-api
