apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-api-service
  labels:
    app: udagram-frontend-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: udagram-frontend-api
