apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-api-service
  labels:
    app: udagram-frontend-api
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-frontend-api
