apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: udagram-reverseproxy
  type: LoadBalancer
